apiVersion: apps/v1
kind: Deployment
metadata:
  name: websitehtml
spec:
  selector:
    matchLabels:
      app: websitehtml
  template:
    metadata:
      labels:
        app: githubactions-aks-demo
    spec:
      containers:
      - name: websitehtml
        image: samplecontaineracr001.azurecr.io/websitehtml
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80