name: Build  Container Image and Push to ACR

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: dockercontent
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: samplecontaineracr001.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t samplecontaineracr001.azurecr.io/websitehtml:${{ github.sha }} 
        docker push samplecontaineracr001.azurecr.io/websitehtml:${{ github.sha }}