name: Deploy Container Image to Azure webapp 

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: dockercontent
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: devlopmentacr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build -t devlopmentacr.azurecr.io/websitehtml:${{ github.sha }} .
        docker push devlopmentacr.azurecr.io/websitehtml:${{ github.sha }}     
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'demotwebapp002'
        images: 'devlopmentacr.azurecr.io/websitehtml:${{ github.sha }}'
    
    - name: Azure logout
      run: |
       az logout
       
